language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}

install:
  - composer install --no-interaction --dev --prefer-source

script: phpunit

notifications:
  email:
    - iman@imanpage.com

